version: '3.8'

services:
  metabase:
    image: metabase/metabase:v0.48.9
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_HOST=postgres
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase_user
      - MB_DB_PASS=metabase_pass
      - MB_DB_DBNAME=metabase
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: metabase-postgres
    environment:
      POSTGRES_USER: metabase_user
      POSTGRES_PASSWORD: metabase_pass
      POSTGRES_DB: metabase
    volumes:
      - metabase-db:/var/lib/postgresql/data

volumes:
  metabase-db:

